global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus itself

  - job_name: 'fio-metrics-exporter'
    static_configs:
      - targets: ['fio-metrics-exporter:9290'] # localhost fio metrics collector
